name: Deploy to GitHub Pages
description: Deploy artifact to GitHub Pages using the Pages API

inputs:
  artifact_id:
    description: The artifact ID from upload-pages-artifact
    required: true

outputs:
  page_url:
    description: The URL of the deployed GitHub Pages site
    value: ${{ steps.deploy.outputs.page_url }}

runs:
  using: composite
  steps:
    - name: Deploy to GitHub Pages
      id: deploy
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
        ARTIFACT_ID: ${{ inputs.artifact_id }}
      with:
        script: |
          const idToken = await core.getIDToken()
          const response = await fetch(
            `https://api.github.com/repos/${context.repo.owner}/${context.repo.repo}/pages/deployments`,
            {
              method: 'POST',
              headers: {
                Accept: 'application/vnd.github+json',
                Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
                'X-GitHub-Api-Version': '2022-11-28',
              },
              body: JSON.stringify({
                artifact_id: Number(process.env.ARTIFACT_ID),
                pages_build_version: context.sha,
                oidc_token: idToken,
              }),
            },
          )

          if (response.ok) {
            const data = await response.json()
            core.setOutput('page_url', data.page_url)
          } else {
            const error = await response.text()
            core.setFailed(`Deploy failed: ${response.status} ${error}`)
          }
