name: Save VRT Cache

on:
  push:
    branches:
      - main

jobs:
  save-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Copy example files
        run: mkdir -p example/.reg && cp -r example/expected example/.reg

      - name: Get commit hash
        id: get-hash
        run: echo "hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Save snapshots cache
        uses: actions/cache/save@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: example/.reg/
          key: reg-${{ steps.get-hash.outputs.hash }}
